easeldriver)
    name="EaselDriver"
    type="pkg"
    packageID="com.inventables.iris-node
com.inventables.iris-lib
com.inventables.iris-daemon"
    downloadURL="https://s3.amazonaws.com/easel-prod/paperclip/sender_version_mac_installers/59/original/EaselDriver.pkg?1767717066"
    appNewVersion=""
    expectedTeamID="3697SB42N2"
    ;;
